name: Test Slack
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Slack Integration
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          # Check if environment variable is set
          if [ -z "$SLACK_WEBHOOK" ]; then
            echo "❌ SLACK_WEBHOOK not set!"
            exit 1
          else
            echo "✅ SLACK_WEBHOOK is configured"
          
            # Send test message
            echo "📤 Sending test message to Slack..."
          
            response=$(curl -s -X POST -H 'Content-type: application/json' \
              --data '{"text":"🎉 Slack integration is working! This is a test from GitHub Actions."}' \
              "$SLACK_WEBHOOK")
          
            echo "Response: $response"
          
            if [ "$response" = "ok" ]; then
              echo "✅ Message sent successfully! Check your Slack channel."
            else
              echo "❌ Unexpected response: $response"
            fi
          fi